### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by Hoku113** [face-pass/E-gate#3]
開発環境をある程度揃えるために各自以下のソフトとモジュールを必ずインストールしてください。

環境構築が済んだものに関してはチェックボックスに随時チェックを入れていってください。

@OgawaYujiro 

- [x] Visual Studio Code
- [x] Python 3.9
  - [x] opencv-python
  - [x] azure
  - [x] azure-cognitive-services-vision-face
  - [x] pymysql
  - [x] Tkinter
  - [x] Azure-storage-blob 12.0.0
- [x] Postman
- [x] git

@ducmanh96 
- [x] Visual Studio Code
- [x] Python 3.9
  - [x] opencv-python
  - [x] azure
  - [x] azure-cognitive-services-vision-face
  - [x] pymysql
  - [x] Tkinter
  - [x] Azure-storage-blob 12.0.0
- [x] Postman
- [x] git

@kazuki13 
- [x] Visual Studio Code
- [x] Python 3.9
  - [x] opencv-python
  - [x] azure
  - [x] azure-cognitive-services-vision-face
  - [x] pymysql
  - [x] Tkinter
  - [x] Azure-storage-blob 12.0.0
- [x] Postman
- [x] git

**Comment by ducmanh96** [comment]
僕から環境構築を完成した。後で画面を共有しながらチェックすることをお願いします。
